Add character detail view
KopytinKa/MyComics pull request #7
Opened 2023-07-10 13:15 UTC by AndreyPiskunov

Добавил предварительно вью с деталями персонажа

2023-07-10 13:45 UTC, Zentaur0 requested changes
Кидаю request changes по сути только из-за строки 

`navigationController?.navigationBar.prefersLargeTitles = false`

потому что при возврате на экран персонажей, у него сломается лардж тайтл.

2023-07-10 13:45 UTC, Zentaur0 commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +    private var presenter: DetailCharacterViewOutput
let

2023-07-10 13:45 UTC, Zentaur0 commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +    private lazy var image = UIImage(named: "characterImage")
- let
- у нас есть экстеншен для зашитых картинок в файле UIImage + Extensions. Чтобы можно было не строки везде переиспользовать, а использовать конкретные статичные картинки UIImage. (прим.: UIImage.demoCharacter)

2023-07-10 13:45 UTC, Zentaur0 commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +    private lazy var characterImageView = UIImageView(image: image)
собственно можно вообще избавиться от свойства image и инициализировать картинку напрямую.
`private let characterImageView = UIImageView(image: .demoCharacter)`
Хотя я понимаю, что она удалиться в любом случае потом, когда будет наполнение данными.

2023-07-10 13:45 UTC, Zentaur0 commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +    private lazy var nameCharacterLabel: UILabel = {
let

2023-07-10 13:45 UTC, Zentaur0 commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +    private lazy var descriptionLabel: UILabel = {
let

2023-07-10 13:45 UTC, Zentaur0 commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +        characterImageView.translatesAutoresizingMaskIntoConstraints = false
эта строка уже есть выше при настройке констрейнтов.

2023-07-10 13:45 UTC, Zentaur0 commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +        characterImageView.contentMode = .scaleAspectFit
плюс давай приведем к общему виду весь экран. Если ты создаешь все свойства и настраиваешь их сразу же на месте через 

`let view: UIView = {
    ...
}()`

то стоит так же поступить с картинкой.

2023-07-10 13:45 UTC, Zentaur0 commented on MyComics/Flows/Characters/Coordinator/CharactersScreenCoordinator.swift
> +        navigationController?.navigationBar.prefersLargeTitles = false
так лучше не делать, это меняет состояние для всего навигейшен бара в стаке навигейшен контроллера. 
Внутри класса DetailCharacterViewController просто добавь 
`navigationItem.largetTitleDisplayMode = .never`

2023-07-10 13:45 UTC, Zentaur0 commented on MyComics/Flows/Characters/Coordinator/CharactersScreenCoordinator.swift
> +        let viewController = DetailCharacterModuleBuilder.build()
я так понимаю, что тебе нужно в метод build прикидывать characterID, чтобы потом по нему грузить контент себе.

2023-07-10 14:28 UTC, AndreyPiskunov commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +    private var presenter: DetailCharacterViewOutput
```suggestion
    private let presenter: DetailCharacterViewOutput
```

2023-07-10 14:37 UTC, AndreyPiskunov commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +    private var presenter: DetailCharacterViewOutput
```suggestion
    private let presenter: DetailCharacterViewOutput
```

2023-07-10 14:57 UTC, AndreyPiskunov commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +    private lazy var image = UIImage(named: "characterImage")
```suggestion

```

2023-07-10 15:00 UTC, AndreyPiskunov commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +    private lazy var nameCharacterLabel: UILabel = {
```suggestion
    private let nameCharacterLabel: UILabel = {
```

2023-07-10 15:02 UTC, AndreyPiskunov commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +        characterImageView.translatesAutoresizingMaskIntoConstraints = false
```suggestion
   
```

2023-07-10 15:03 UTC, AndreyPiskunov commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +        characterImageView.translatesAutoresizingMaskIntoConstraints = false
```suggestion

```

2023-07-10 15:06 UTC, AndreyPiskunov commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +    private var presenter: DetailCharacterViewOutput
```suggestion
    private let presenter: DetailCharacterViewOutput
```

2023-07-10 15:06 UTC, AndreyPiskunov commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +    private lazy var image = UIImage(named: "characterImage")
```suggestion

```

2023-07-10 15:07 UTC, AndreyPiskunov commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +    private lazy var characterImageView = UIImageView(image: image)
```suggestion
    private let characterImageView = UIImageView(image: .characterPlaceholder)
```

2023-07-10 15:07 UTC, AndreyPiskunov commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +    private lazy var nameCharacterLabel: UILabel = {
```suggestion
    private let nameCharacterLabel: UILabel = {
```

2023-07-10 15:10 UTC, AndreyPiskunov commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +    private lazy var descriptionLabel: UILabel = {
```suggestion
    private let descriptionLabel: UILabel = {
```

2023-07-10 15:13 UTC, AndreyPiskunov commented on MyComics/Flows/Characters/Coordinator/CharactersScreenCoordinator.swift
> +        navigationController?.navigationBar.prefersLargeTitles = false
```suggestion

```

2023-07-10 15:26 UTC, AndreyPiskunov commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +        view.backgroundColor = .commonBackground
```suggestion
        navigationItem.largeTitleDisplayMode = .never
        view.backgroundColor = .commonBackground
```

поправил баг навигейшен бара

2023-07-10 15:26 UTC, AndreyPiskunov commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +        view.backgroundColor = .commonBackground
поправил баг навигейшена

2023-07-10 15:39 UTC, AndreyPiskunov commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +        characterImageView.contentMode = .scaleAspectFit
```suggestion

```

2023-07-10 15:55 UTC, AndreyPiskunov commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +        characterImageView.contentMode = .scaleAspectFit
```suggestion

```

2023-07-10 15:56 UTC, AndreyPiskunov commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +    }
```suggestion

```

2023-07-10 16:12 UTC, Zentaur0 approved these changes

2023-07-11 07:02 UTC, AndreyPiskunov commented on MyComics/Flows/DetailCharacter/View/DetailCharacterViewController.swift
> +    private lazy var characterImageView = UIImageView(image: image)
```suggestion
    private let characterImageView: UIImageView = {
        let characterImageView = UIImageView(image: .characterPlaceholder)
        characterImageView.contentMode = .scaleAspectFit
        return characterImageView
    }()
```
инициализация image

2023-07-11 07:18 UTC, merged